### ISSUE TITLE
Not an issue but a question: can this write to two different log groups

### ISSUE THREAD

**Issue by quapaw** [KyleRoss/node-lambda-log#18]
I am trying to find a way to write to two different Cloud Watch Groups from Lambda node.js

**Comment by dimkir** [comment]
From what I remember the default way logging works on lambda is like this: 

 - all console.log  & console.error & console.warn are all redirected to STDOUT 
 - each line added to STDOUT  (by direct writing to STDOUT or via using console.xxx() is added to CloudWatch (with timestamp and requestId added as prefix)
 - the "plumbing" of taking STDOUT line and putting it into CloudWatch is done by the lambda framework (and not by a userland library akin to lambda-log)
 - in order for the "plumbing" to work you must specify within IAM permissions for labmda to write to specific log group (in other words: even though "plumbing" happens on AWS side, we still have to explicitly grant permissions to write to CW log group)
 - if you want to write to a second CW Log group, then you have to implement it manually (see below) 

ps.  Just another quirk I discovered about Lambda: if you write from lambda manually to STDERR (eg. via `process.stderr.write("Message for STDERR")`  your message may or may not appear in the CloudWatch logs (it seems to be it is an undocumented behaviour, so I wouldn't rely on it). But if it appears, it appears without Timestamp and RequestId (which can mess up your log parsers or metric rules).  If I remember correclty `debug`  npm package by default writes to STDERR.

### Manually writing to two different log groups 
 - the default log group will be written automatically (by the mechanism described above)
 - you have to create new log group (eg. `altgroup01`) before running lambda
 - you have to add IAM permissions to your lambda function to write to CW Log group (which in AWS slang is called: "put events to CW log group")
 - under the hood you will need to call  AWS API  `put-log-events` https://docs.aws.amazon.com/cli/latest/reference/logs/put-log-events.html
 - The most trivial (but not reccommneded) way would be to pepper your code with `put-log-event` API call 

However in order to make writing to two log groups neat and clean you can either:
  a) If you don't use any external libraries then you have to override `console.log/warn/info/error` with your own function in global namespace (in case your codebase already logs with `console.xxx` functions and you don't want to change the code)
 b) if you are in a position to use external logging library (eg. `lambda-log` ) then you will need to code up  your custom `logHandler` and wire it up with the logging library ( eg. https://github.com/KyleRoss/node-lambda-log/blob/master/lib/LambdaLog.js#L88 ) 

Hope this helps.

**Comment by KyleRoss** [comment]
In order to write to separate log groups, you would need to use the AWS SDK in order to directly write. A single process can only write to one log group because of AWS's limitations of how it pipes console messages to CloudWatch logs.

There could be other packages out there that could do this, but I haven't seen one in particular.
