### ISSUE TITLE
Dynamic metadata async/promise

### ISSUE THREAD

**Issue by bikerp** [KyleRoss/node-lambda-log#19]
Hi,
is it possible to use Promise for Dynamic metadata function?
Thanks
Pavel

**Comment by KyleRoss** [comment]
Currently there is not a way, but it wouldn't be too difficult to add. I will try to get it in soon.

**Comment by KyleRoss** [comment]
Since lambda-log and console by nature is synchronous, it becomes difficult to add asynchronous aspects. While it could be done, it would ultimately delay the log or prevent the log from being written if the promise fails to resolve.

The more I think about it, I'm not sure of any case in which you'd want to have a promise return dynamic metadata for a log message. If you are looking to add user information or something along those lines in which comes from an asynchronous source, I'd suggest loading and storing that information at the beginning and then including that information into the metadata for the log.

Feel free to reopen this issue if you have a good use case and I can further investigate the lift to add it.

**Comment by bikerp** [comment]
Hi @KyleRoss 
thank you for your feedback. I have solved my use case in similar way as you suggested.
So this feature is really not necessary.
Cheers
Pavel
