### ISSUE TITLE
Support for undefined

### ISSUE THREAD

**Issue by e02d96ec16** [KyleRoss/node-lambda-log#6]
Passing to the meta/msg something that is `undefined` will make it not show up that (k,v) pair at all.

This is not desirable when logging values of symbols.

### Example
```
var myVar = undefined
logger.log("debug", "the value of myVar", { value: myVar })
```

**Comment by e02d96ec16** [comment]
Am I misunderstanding something here about how to use this? Because neither are strings supported: they will show up as `{}`.

**Comment by KyleRoss** [comment]
@e02d96ec16 Can you give an example for your second comment?

As for your first comment, I have tested this and it is working. I see `{ value: undefined }` show up in the resulting object. The issue is that in order to log the message, it needs converted to JSON using `JSON.stringify` which will remove any variables which are `undefined` as there is no format in JSON for `undefined`. If you need to have that variable show up, you would be better off setting it as `null` instead.

**Comment by e02d96ec16** [comment]
@KyleRoss Thanks for your answers!
